### ISSUE TITLE
support for Swift6

### ISSUE THREAD

**Issue by EagleKang** [Tencent/wcdb#1120]
### The language of WCDB

>Swift

### The version of WCDB
v2.1.6

### The platform of WCDB

iOS

### The installation of WCDB
Swift Package Manager

### What's the issue?
this is a warning: Non-final class 'Sample' cannot safely conform to protocol 'TableEncodable', which requires that 'Self.CodingKeys.Root' is exactly equal to 'Self'; this is an error in Swift 6

**Comment by Qiuwen-chen** [comment]
I will fix it in the next version, please wait.

**Comment by Qiuwen-chen** [comment]
Fixed in v2.1.7

**Comment by sunsang** [comment]
I updated to 2.1.7, but still have this warning  Is there something wrong?

**Comment by kelijun** [comment]
> 我已更新到 2.1.7，但仍然有此警告，有什么问题吗？
final class / struct

**Comment by sunsang** [comment]
> > 我已更新到 2.1.7，但仍然有此警告，有什么问题吗？
> > final class / struct

但是需要使用继承😂
